#!/usr/bin/env python3
"""
Build script for Kitchen Quote Management System
Creates a standalone EXE file using PyInstaller
"""

import os
import sys
import shutil
import subprocess
from pathlib import Path

def check_dependencies():
    """Check if required build dependencies are installed"""
    required_packages = ['PyInstaller']
    missing = []
    
    for package in required_packages:
        try:
            __import__(package.lower())
        except ImportError:
            missing.append(package)
    
    if missing:
        print(f"Missing required packages: {', '.join(missing)}")
        print("Install them with: pip install PyInstaller")
        return False
    
    return True

def clean_build_dirs():
    """Clean previous build directories"""
    dirs_to_clean = ['build', 'dist', '__pycache__']
    
    for dir_name in dirs_to_clean:
        if os.path.exists(dir_name):
            print(f"Cleaning {dir_name}...")
            shutil.rmtree(dir_name)
    
    # Clean .spec files
    for spec_file in Path('.').glob('*.spec'):
        print(f"Removing {spec_file}...")
        spec_file.unlink()

def create_pyinstaller_spec():
    """Create PyInstaller spec file"""
    spec_content = '''# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# Additional data files to include
added_files = [
    ('resources/*', 'resources'),
    ('config/settings.json', 'config'),
    ('requirements.txt', '.'),
    ('README.md', '.'),
]

# Hidden imports that PyInstaller might miss
hidden_imports = [
    'customtkinter',
    'PIL._tkinter_finder',
    'tkinter',
    'tkinter.ttk',
    'sqlite3',
    'sqlalchemy.sql.default_comparator',
    'sqlalchemy.ext.baked',
    'pandas._libs.tslibs.timedeltas',
    'openpyxl.pivot',
    'reportlab.graphics',
    'reportlab.lib.styles',
    'cryptography',
    'arabic_reshaper',
    'bidi',
]

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=added_files,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy.testing',
        'pytest',
        'setuptools',
        'distutils',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='KitchenQuoteManager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # Set to True for debugging
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='resources/White_Logo.ico' if os.path.exists('resources/White_Logo.ico') else None,
)
'''
    
    with open('kitchen_quotes.spec', 'w', encoding='utf-8') as f:
        f.write(spec_content)
    
    print("Created PyInstaller spec file: kitchen_quotes.spec")

def build_exe():
    """Build the EXE file"""
    print("Building EXE file...")
    
    # Run PyInstaller
    cmd = [
        sys.executable, '-m', 'PyInstaller',
        '--clean',
        '--noconfirm',
        'kitchen_quotes.spec'
    ]
    
    try:
        result = subprocess.run(cmd, check=True, capture_output=True, text=True)
        print("Build completed successfully!")
        
        # Check if EXE was created
        exe_path = Path('dist/KitchenQuoteManager.exe')
        if exe_path.exists():
            size_mb = exe_path.stat().st_size / (1024 * 1024)
            print(f"EXE created: {exe_path}")
            print(f"Size: {size_mb:.1f} MB")
            return True
        else:
            print("ERROR: EXE file was not created!")
            return False
            
    except subprocess.CalledProcessError as e:
        print(f"Build failed with error: {e}")
        print(f"Error output: {e.stderr}")
        return False

def create_installer_script():
    """Create NSIS installer script (optional)"""
    nsis_script = '''
; Kitchen Quote Management System Installer
; Generated by build script

!define APPNAME "Kitchen Quote Management System"
!define COMPANYNAME "Kitchen Studio"
!define DESCRIPTION "מערכת ניהול הצעות מטבח"
!define VERSIONMAJOR 1
!define VERSIONMINOR 0
!define VERSIONBUILD 0
!define HELPURL "https://github.com/your-repo/kitchen-quotes"
!define UPDATEURL "https://github.com/your-repo/kitchen-quotes"
!define ABOUTURL "https://kitchen-studio.co.il"
!define INSTALLSIZE 50000  ; Estimate in KB

RequestExecutionLevel admin
InstallDir "$PROGRAMFILES\\${COMPANYNAME}\\${APPNAME}"
Name "${APPNAME}"
outFile "KitchenQuoteManager_Setup.exe"

page directory
page instfiles

section "install"
    setOutPath $INSTDIR
    
    ; Copy application files
    file /r "dist\\KitchenQuoteManager.exe"
    
    ; Create uninstaller
    writeUninstaller "$INSTDIR\\uninstall.exe"
    
    ; Create start menu shortcut
    createDirectory "$SMPROGRAMS\\${COMPANYNAME}"
    createShortCut "$SMPROGRAMS\\${COMPANYNAME}\\${APPNAME}.lnk" "$INSTDIR\\KitchenQuoteManager.exe"
    
    ; Create desktop shortcut
    createShortCut "$DESKTOP\\${APPNAME}.lnk" "$INSTDIR\\KitchenQuoteManager.exe"
    
    ; Registry information for add/remove programs
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" "DisplayName" "${APPNAME}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" "UninstallString" "$INSTDIR\\uninstall.exe"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" "InstallLocation" "$INSTDIR"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" "Publisher" "${COMPANYNAME}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" "HelpLink" "${HELPURL}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" "URLUpdateInfo" "${UPDATEURL}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" "URLInfoAbout" "${ABOUTURL}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" "DisplayVersion" "${VERSIONMAJOR}.${VERSIONMINOR}.${VERSIONBUILD}"
    WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" "EstimatedSize" ${INSTALLSIZE}
sectionEnd

; Uninstaller
section "uninstall"
    delete "$INSTDIR\\KitchenQuoteManager.exe"
    delete "$INSTDIR\\uninstall.exe"
    rmDir "$INSTDIR"
    
    ; Remove shortcuts
    delete "$SMPROGRAMS\\${COMPANYNAME}\\${APPNAME}.lnk"
    rmDir "$SMPROGRAMS\\${COMPANYNAME}"
    delete "$DESKTOP\\${APPNAME}.lnk"
    
    ; Remove registry entries
    DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}"
sectionEnd
'''
    
    with open('installer.nsi', 'w', encoding='utf-8') as f:
        f.write(nsis_script)
    
    print("Created NSIS installer script: installer.nsi")
    print("To create installer, install NSIS and run: makensis installer.nsi")

def optimize_exe():
    """Apply optimizations to reduce EXE size"""
    exe_path = Path('dist/KitchenQuoteManager.exe')
    
    if not exe_path.exists():
        print("EXE file not found for optimization")
        return
    
    print("EXE optimization tips:")
    print("1. The EXE includes Python runtime and all dependencies")
    print("2. Size can be reduced by excluding unused modules")
    print("3. Consider using --onedir instead of --onefile for faster startup")
    print("4. UPX compression is enabled to reduce size")

def main():
    """Main build process"""
    print("Kitchen Quote Management System - EXE Builder")
    print("=" * 50)
    
    # Check dependencies
    if not check_dependencies():
        return 1
    
    # Clean previous builds
    clean_build_dirs()
    
    # Create spec file
    create_pyinstaller_spec()
    
    # Build EXE
    if build_exe():
        print("\n✅ Build completed successfully!")
        
        # Create installer script
        create_installer_script()
        
        # Show optimization info
        optimize_exe()
        
        print("\nNext steps:")
        print("1. Test the EXE: dist/KitchenQuoteManager.exe")
        print("2. Optionally create installer with NSIS")
        print("3. Distribute to users")
        
        return 0
    else:
        print("\n❌ Build failed!")
        return 1

if __name__ == "__main__":
    sys.exit(main()) 